### ISSUE TITLE
Switch from Joystick to Xbox Controller for driving

### ISSUE THREAD

**Issue by dillontherrien** [dillontherrien/7913-FRC-2022#4]
Using this [XboxController class](https://first.wpi.edu/FRC/roborio/release2017/docs/java/edu/wpi/first/wpilibj/XboxController.html)

**Comment by BruceMcRooster** [comment]
As far as I can tell, this doesn't actually need that much. I checked all the references to src/main/java/org/usfirst/frc7913/Main/IO.java and its controllers, and the only one exists in src/main/java/org/usfirst/frc7913/Main/subsystems/DriveTrain.java. I'm not quite sure what `joystickx30` is, if it's the joystick that I know we have or something else, but as long as it works with the Xbox controller class, it should be fine. The only references to function on it are .getX() and .getY() in `Drivetrain.java`, and these both come by inheritance from `GenericHID` class, so they should work the same. Unless you have any objections, a PR that literally just switches the names should work.

**Comment by dillontherrien** [comment]
We also need to switch from using the ArcadeDrive method to the TankDrive one. It is necessary so you can get the y axis from both controller sticks

**Comment by dillontherrien** [comment]
#9 Resolves this issue
